<a href="https://colab.research.google.com/github/SuyashPant04/Spam-Classifier/blob/main/SpamClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [90]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [91]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Spam/spam.csv', encoding='latin1')

In [92]:
data.head()

v1                                                 v2 Unnamed: 2  \
0   ham  Go until jurong point, crazy.. Available only ...        NaN   
1   ham                      Ok lar... Joking wif u oni...        NaN   
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...        NaN   
3   ham  U dun say so early hor... U c already then say...        NaN   
4   ham  Nah I don't think he goes to usf, he lives aro...        NaN   

  Unnamed: 3 Unnamed: 4  
0        NaN        NaN  
1        NaN        NaN  
2        NaN        NaN  
3        NaN        NaN  
4        NaN        NaN

In [93]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [94]:
data = data.drop(columns = data.columns[-3:])

In [95]:
data

v1                                                 v2
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [96]:

import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_r

True

In [97]:
data = data.rename(columns = {'v1': 'Label', 'v2': 'Text'})

In [98]:
data['Text'].dropna(inplace=True)

In [99]:
data

Label                                               Text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [100]:
# Converting all entries in 'text' to lowercase in case they are not
data['Text'] = [entry.lower() for entry in data['Text']]

In [101]:
from sklearn.preprocessing import LabelEncoder
from nltk.tokenize import word_tokenize

In [102]:
data['Text']= [word_tokenize(entry) for entry in data['Text']]

In [103]:
data.head()

Label                                               Text
0   ham  [go, until, jurong, point, ,, crazy, .., avail...
1   ham           [ok, lar, ..., joking, wif, u, oni, ...]
2  spam  [free, entry, in, 2, a, wkly, comp, to, win, f...
3   ham  [u, dun, say, so, early, hor, ..., u, c, alrea...
4   ham  [nah, i, do, n't, think, he, goes, to, usf, ,,...

In [104]:
from nltk.stem import WordNetLemmatizer
from collections import defaultdict
from nltk.corpus import wordnet as wn
from nltk.corpus import stopwords
from nltk import pos_tag

In [105]:
tag_map = defaultdict(lambda : wn.NOUN)
tag_map['J'] = wn.ADJ
tag_map['V'] = wn.VERB
tag_map['R'] = wn.ADV
word_Lemmatizer = WordNetLemmatizer()

In [106]:
print(tag_map)
data['Text']

defaultdict(<function <lambda> at 0x792d32fda680>, {'J': 'a', 'V': 'v', 'R': 'r'})


0       [go, until, jurong, point, ,, crazy, .., avail...
1                [ok, lar, ..., joking, wif, u, oni, ...]
2       [free, entry, in, 2, a, wkly, comp, to, win, f...
3       [u, dun, say, so, early, hor, ..., u, c, alrea...
4       [nah, i, do, n't, think, he, goes, to, usf, ,,...
                              ...                        
5567    [this, is, the, 2nd, time, we, have, tried, 2,...
5568     [will, ì_, b, going, to, esplanade, fr, home, ?]
5569    [pity, ,, *, was, in, mood, for, that, ., so, ...
5570    [the, guy, did, some, bitching, but, i, acted,...
5571                  [rofl, ., its, true, to, its, name]
Name: Text, Length: 5572, dtype: object

In [107]:
for index, entry in enumerate(data['Text']):
    Final_words = []
    for word, tag in pos_tag(entry):
        if word not in stopwords.words('english') and word.isalpha():
            word_Final = word_Lemmatizer.lemmatize(word,pos = tag_map[tag[0]])
            Final_words.append(word_Final)
    data.loc[index,'final'] = str(Final_words)


In [108]:
data

Label                                               Text  \
0      ham  [go, until, jurong, point, ,, crazy, .., avail...   
1      ham           [ok, lar, ..., joking, wif, u, oni, ...]   
2     spam  [free, entry, in, 2, a, wkly, comp, to, win, f...   
3      ham  [u, dun, say, so, early, hor, ..., u, c, alrea...   
4      ham  [nah, i, do, n't, think, he, goes, to, usf, ,,...   
...    ...                                                ...   
5567  spam  [this, is, the, 2nd, time, we, have, tried, 2,...   
5568   ham   [will, ì_, b, going, to, esplanade, fr, home, ?]   
5569   ham  [pity, ,, *, was, in, mood, for, that, ., so, ...   
5570   ham  [the, guy, did, some, bitching, but, i, acted,...   
5571   ham                [rofl, ., its, true, to, its, name]   

                                                  final  
0     ['go', 'jurong', 'point', 'crazy', 'available'...  
1              ['ok', 'lar', 'joke', 'wif', 'u', 'oni']  
2     ['free', 'entry', 'wkly', 'comp', 'win', 'fa',...  
3     ['u', 'dun', 'say', 'early', 'hor', 'u', 'c', ...  
4     ['nah', 'think', 'go', 'usf', 'live', 'around'...  
...                                                 ...  
5567  ['time', 'try', 'contact', 'u', 'pound', 'priz...  
5568             ['b', 'go', 'esplanade', 'fr', 'home']  
5569                     ['pity', 'mood', 'suggestion']  
5570  ['guy', 'bitching', 'act', 'like', 'interested...  
5571                           ['rofl', 'true', 'name']  

[5572 rows x 3 columns]

In [118]:
Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(data['final'],data['Label'],test_size=0.15)

In [119]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score

**Data Encoding(TFIDF)**

In [132]:
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)

In [133]:
Tfidf_vect = TfidfVectorizer(max_features=3000)
Tfidf_vect.fit(data['final'])

TfidfVectorizer(max_features=3000)

In [134]:
Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

**Data Encoding(Count Vectorizer)**

In [135]:
from sklearn.feature_extraction.text import CountVectorizer

In [145]:
vectorizer = CountVectorizer(max_features=5000)

vectorizer.fit(data['final'])

CountVectorizer(max_features=5000)

In [146]:
# Printing the identified Unique words along with their indices
print("Vocabulary: ", vectorizer.vocabulary_)

Vocabulary:  {'go': 1980, 'point': 2885, 'crazy': 1029, 'available': 382, 'bugis': 632, 'great': 2008, 'world': 4855, 'la': 2332, 'buffet': 631, 'cine': 820, 'get': 1963, 'amore': 188, 'wat': 4687, 'ok': 2745, 'lar': 2343, 'joke': 2276, 'wif': 4782, 'oni': 2754, 'free': 1865, 'entry': 1539, 'wkly': 4822, 'comp': 905, 'win': 4791, 'fa': 1655, 'cup': 1077, 'final': 1745, 'tkts': 4279, 'may': 2518, 'text': 4165, 'receive': 3151, 'question': 3064, 'std': 3883, 'txt': 4428, 'rate': 3108, 'apply': 266, 'dun': 1419, 'say': 3409, 'early': 1435, 'hor': 2118, 'already': 166, 'nah': 2654, 'think': 4210, 'usf': 4548, 'live': 2405, 'around': 304, 'though': 4226, 'freemsg': 1871, 'hey': 2084, 'darling': 1124, 'week': 4720, 'word': 4848, 'back': 419, 'like': 2389, 'fun': 1920, 'still': 3904, 'tb': 4118, 'xxx': 4907, 'chgs': 797, 'send': 3479, 'rcv': 3118, 'even': 1581, 'brother': 618, 'speak': 3787, 'treat': 4374, 'aid': 124, 'per': 2830, 'request': 3231, 'melle': 2540, 'oru': 2776, 'minnaminunginte'

In [147]:
# Encoding the Document
Train_X_CV = vectorizer.transform(Train_X)
Test_X_CV = vectorizer.transform(Test_X)

In [148]:
print("Encoded Documents are:")
print(Train_X_CV.toarray())
print(Test_X_CV.toarray())

Encoded Documents are:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


**Naive Bayes(TFIDF)**

In [149]:
# Implementing the Multinomial Naive Bayes model
NB = naive_bayes.MultinomialNB()
NB.fit(Train_X_Tfidf,Train_Y)

MultinomialNB()

In [150]:
# Predicting the labels on validation dataset
pred_NB_tfidf = NB.predict(Test_X_Tfidf)

In [151]:

# Using accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(pred_NB_tfidf, Test_Y)*100)

Naive Bayes Accuracy Score ->  96.41148325358851


**Naive Bayes(Count Vectorizer)**

In [152]:
# Implementing the Multinomial Naive Bayes model
NB = naive_bayes.MultinomialNB()
NB.fit(Train_X_CV,Train_Y)

MultinomialNB()

In [153]:
# Predicting the labels on validation dataset
pred_NB_cv = NB.predict(Test_X_CV)

In [155]:
# Using accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(pred_NB_cv, Test_Y)*100)

Naive Bayes Accuracy Score ->  95.69377990430623


**SVM(TFIDF)**

In [166]:
#Implementing SVM and setting the parameters
SVM = svm.SVC(C = 1.0, kernel = 'linear', degree = 3, gamma = 'auto')

In [167]:
SVM.fit(Train_X_Tfidf, Train_Y)

SVC(gamma='auto', kernel='linear')

In [168]:
pred_SVM_tfidf = SVM.predict(Test_X_Tfidf)

In [169]:
print("SVM Accuracy Score -> ",accuracy_score(pred_SVM, Test_Y)*100)

SVM Accuracy Score ->  97.48803827751196


**SVM(CountVectorizer)**

In [170]:
#Implementing SVM and setting the parameters
SVM = svm.SVC(C = 1.0, kernel = 'linear', degree = 3, gamma = 'auto')

In [171]:
SVM.fit(Train_X_CV, Train_Y)

SVC(gamma='auto', kernel='linear')

In [173]:
pred_SVM_cv = SVM.predict(Test_X_CV)

In [174]:
print("SVM Accuracy Score -> ",accuracy_score(pred_SVM_cv, Test_Y)*100)

SVM Accuracy Score ->  98.32535885167464
