<a href="https://colab.research.google.com/github/SuyashPant04/Spam-Classifier/blob/main/SpamClassifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [5]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Spam/spam.csv', encoding='latin1')

In [6]:
data.head()

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN


In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   v1          5572 non-null   object
 1   v2          5572 non-null   object
 2   Unnamed: 2  50 non-null     object
 3   Unnamed: 3  12 non-null     object
 4   Unnamed: 4  6 non-null      object
dtypes: object(5)
memory usage: 217.8+ KB


In [8]:
data = data.drop(columns = data.columns[-3:])

In [9]:
data

,v1,v2
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will Ì_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [10]:

import nltk
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    | 
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |  

True

In [11]:
data = data.rename(columns = {'v1': 'Label', 'v2': 'Text'})

In [12]:
data['Text'].dropna(inplace=True)

In [13]:
data

,Label,Text
0,ham,"Go until jurong point, crazy.. Available only ..."
1,ham,Ok lar... Joking wif u oni...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...
3,ham,U dun say so early hor... U c already then say...
4,ham,"Nah I don't think he goes to usf, he lives aro..."
...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...
5568,ham,Will Ì_ b going to esplanade fr home?
5569,ham,"Pity, * was in mood for that. So...any other s..."
5570,ham,The guy did some bitching but I acted like i'd...


In [14]:
# Converting all entries in 'text' to lowercase in case they are not
data['Text'] = [entry.lower() for entry in data['Text']]

In [15]:
from sklearn.preprocessing import LabelEncoder
from nltk.tokenize import word_tokenize

In [16]:
data['Text']= [word_tokenize(entry) for entry in data['Text']]

In [17]:
data.head()

,Label,Text
0,ham,"[go, until, jurong, point, ,, crazy, .., avail..."
1,ham,"[ok, lar, ..., joking, wif, u, oni, ...]"
2,spam,"[free, entry, in, 2, a, wkly, comp, to, win, f..."
3,ham,"[u, dun, say, so, early, hor, ..., u, c, alrea..."
4,ham,"[nah, i, do, n't, think, he, goes, to, usf, ,,..."


In [18]:
from nltk.stem import WordNetLemmatizer
from collections import defaultdict
from nltk.corpus import wordnet as wn
from nltk.corpus import stopwords
from nltk import pos_tag

In [19]:
tag_map = defaultdict(lambda : wn.NOUN)
tag_map['J'] = wn.ADJ
tag_map['V'] = wn.VERB
tag_map['R'] = wn.ADV
word_Lemmatizer = WordNetLemmatizer()

In [20]:
print(tag_map)
data['Text']

defaultdict(<function <lambda> at 0x7c2580b67ce0>, {'J': 'a', 'V': 'v', 'R': 'r'})


,Text
0,"[go, until, jurong, point, ,, crazy, .., avail..."
1,"[ok, lar, ..., joking, wif, u, oni, ...]"
2,"[free, entry, in, 2, a, wkly, comp, to, win, f..."
3,"[u, dun, say, so, early, hor, ..., u, c, alrea..."
4,"[nah, i, do, n't, think, he, goes, to, usf, ,,..."
...,...
5567,"[this, is, the, 2nd, time, we, have, tried, 2,..."
5568,"[will, ì_, b, going, to, esplanade, fr, home, ?]"
5569,"[pity, ,, *, was, in, mood, for, that, ., so, ..."
5570,"[the, guy, did, some, bitching, but, i, acted,..."


In [21]:
for index, entry in enumerate(data['Text']):
    Final_words = []
    for word, tag in pos_tag(entry):
        if word not in stopwords.words('english') and word.isalpha():
            word_Final = word_Lemmatizer.lemmatize(word,pos = tag_map[tag[0]])
            Final_words.append(word_Final)
    data.loc[index,'final'] = str(Final_words)


In [22]:
data

,Label,Text,final
0,ham,"[go, until, jurong, point, ,, crazy, .., avail...","['go', 'jurong', 'point', 'crazy', 'available'..."
1,ham,"[ok, lar, ..., joking, wif, u, oni, ...]","['ok', 'lar', 'joke', 'wif', 'u', 'oni']"
2,spam,"[free, entry, in, 2, a, wkly, comp, to, win, f...","['free', 'entry', 'wkly', 'comp', 'win', 'fa',..."
3,ham,"[u, dun, say, so, early, hor, ..., u, c, alrea...","['u', 'dun', 'say', 'early', 'hor', 'u', 'c', ..."
4,ham,"[nah, i, do, n't, think, he, goes, to, usf, ,,...","['nah', 'think', 'go', 'usf', 'live', 'around'..."
...,...,...,...
5567,spam,"[this, is, the, 2nd, time, we, have, tried, 2,...","['time', 'try', 'contact', 'u', 'pound', 'priz..."
5568,ham,"[will, ì_, b, going, to, esplanade, fr, home, ?]","['b', 'go', 'esplanade', 'fr', 'home']"
5569,ham,"[pity, ,, *, was, in, mood, for, that, ., so, ...","['pity', 'mood', 'suggestion']"
5570,ham,"[the, guy, did, some, bitching, but, i, acted,...","['guy', 'bitching', 'act', 'like', 'interested..."


In [27]:
from sklearn.model_selection import train_test_split

Train_X, Test_X, Train_Y, Test_Y = model_selection.train_test_split(data['final'],data['Label'],test_size=0.15)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn import model_selection, naive_bayes, svm
from sklearn.metrics import accuracy_score

**Data Encoding(TFIDF)**

In [29]:
Encoder = LabelEncoder()
Train_Y = Encoder.fit_transform(Train_Y)
Test_Y = Encoder.fit_transform(Test_Y)

In [30]:
Tfidf_vect = TfidfVectorizer(max_features=3000)
Tfidf_vect.fit(data['final'])

TfidfVectorizer(max_features=3000)

In [31]:
Train_X_Tfidf = Tfidf_vect.transform(Train_X)
Test_X_Tfidf = Tfidf_vect.transform(Test_X)

**Data Encoding(Count Vectorizer)**

In [32]:
from sklearn.feature_extraction.text import CountVectorizer

In [33]:
vectorizer = CountVectorizer(max_features=5000)

vectorizer.fit(data['final'])

CountVectorizer(max_features=5000)

In [34]:
# Printing the identified Unique words along with their indices
print("Vocabulary: ", vectorizer.vocabulary_)

Vocabulary:  {'go': np.int64(1577), 'jurong': np.int64(2219), 'point': np.int64(3430), 'crazy': np.int64(609), 'available': np.int64(203), 'bugis': np.int64(382), 'great': np.int64(1641), 'world': np.int64(4925), 'la': np.int64(2315), 'buffet': np.int64(381), 'cine': np.int64(499), 'get': np.int64(1541), 'wat': np.int64(4834), 'ok': np.int64(3109), 'lar': np.int64(2343), 'joke': np.int64(2191), 'wif': np.int64(4882), 'oni': np.int64(3133), 'free': np.int64(1420), 'entry': np.int64(1094), 'wkly': np.int64(4908), 'comp': np.int64(546), 'win': np.int64(4889), 'fa': np.int64(1210), 'cup': np.int64(632), 'final': np.int64(1300), 'tkts': np.int64(4626), 'may': np.int64(2650), 'text': np.int64(4564), 'receive': np.int64(3742), 'question': np.int64(3655), 'std': np.int64(4420), 'txt': np.int64(4705), 'rate': np.int64(3699), 'apply': np.int64(151), 'dun': np.int64(974), 'say': np.int64(4000), 'early': np.int64(990), 'hor': np.int64(1870), 'already': np.int64(102), 'nah': np.int64(2892), 'think'

In [35]:
# Encoding the Document
Train_X_CV = vectorizer.transform(Train_X)
Test_X_CV = vectorizer.transform(Test_X)

In [36]:
print("Encoded Documents are:")
print(Train_X_CV.toarray())
print(Test_X_CV.toarray())

Encoded Documents are:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


**Naive Bayes(TFIDF)**

In [37]:
# Implementing the Multinomial Naive Bayes model
NB = naive_bayes.MultinomialNB()
NB.fit(Train_X_Tfidf,Train_Y)

MultinomialNB()

In [38]:
# Predicting the labels on validation dataset
pred_NB_tfidf = NB.predict(Test_X_Tfidf)

In [39]:

# Using accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(pred_NB_tfidf, Test_Y)*100)

Naive Bayes Accuracy Score ->  97.24880382775119


**Naive Bayes(Count Vectorizer)**

In [40]:
# Implementing the Multinomial Naive Bayes model
NB = naive_bayes.MultinomialNB()
NB.fit(Train_X_CV,Train_Y)

MultinomialNB()

In [41]:
# Predicting the labels on validation dataset
pred_NB_cv = NB.predict(Test_X_CV)

In [42]:
# Using accuracy_score function to get the accuracy
print("Naive Bayes Accuracy Score -> ",accuracy_score(pred_NB_cv, Test_Y)*100)

Naive Bayes Accuracy Score ->  96.88995215311004


**SVM(TFIDF)**

In [43]:
#Implementing SVM and setting the parameters
SVM = svm.SVC(C = 1.0, kernel = 'linear', degree = 3, gamma = 'auto')

In [44]:
SVM.fit(Train_X_Tfidf, Train_Y)

SVC(gamma='auto', kernel='linear')

In [45]:
pred_SVM_tfidf = SVM.predict(Test_X_Tfidf)

In [52]:
print("SVM Accuracy Score -> ",accuracy_score(pred_SVM_tfidf, Test_Y)*100)

SVM Accuracy Score ->  98.08612440191388


**SVM(CountVectorizer)**

In [53]:
#Implementing SVM and setting the parameters
SVM = svm.SVC(C = 1.0, kernel = 'linear', degree = 3, gamma = 'auto')

In [54]:
SVM.fit(Train_X_CV, Train_Y)

SVC(gamma='auto', kernel='linear')

In [55]:
pred_SVM_cv = SVM.predict(Test_X_CV)

In [56]:
print("SVM Accuracy Score -> ",accuracy_score(pred_SVM_cv, Test_Y)*100)

SVM Accuracy Score ->  97.96650717703349
